<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('orders')->delete();

        \DB::table('orders')->insert(array (
            0 =>
            array (
                'address' => 'Hell',
                'amount' => 500,
                'card_number' => NULL,
                'charge' => 100,
                'country' => 'Indonesia',

                'email' => 'freakboss3@gmail.com',
                'first_name' => 'Julius',
                'id' => 15,
                'ip_address' => NULL,
                'last_name' => 'Boom',
                'note' => NULL,
                'payment_type' => NULL,
                'phone' => '2345568',
                'product_id' => 3,
                'quantity' => 5,
                'ref_id' => 'RCFckqqCYMrIZaPD',
                'seller_id' => 11,
                'ship_id' => NULL,
                'shipping_fee' => '0',
                'state' => 'Banten',
                'status' => 1,
                'store_id' => NULL,
                'total' => 2500,
                'town' => 'Georgia',

                'user_id' => 27,
            ),
            1 =>
            array (
                'address' => 'Hell',
                'amount' => 500,
                'card_number' => NULL,
                'charge' => 80,
                'country' => 'Algeria',

                'email' => 'freakboss3@gmail.com',
                'first_name' => 'Julius',
                'id' => 16,
                'ip_address' => NULL,
                'last_name' => 'Boom',
                'note' => NULL,
                'payment_type' => NULL,
                'phone' => '2345568',
                'product_id' => 3,
                'quantity' => 4,
                'ref_id' => 'R02diqM8cXivXM2Z',
                'seller_id' => 11,
                'ship_id' => NULL,
                'shipping_fee' => '0',
                'state' => 'Ain Temouchent',
                'status' => 1,
                'store_id' => NULL,
                'total' => 2000,
                'town' => 'Georgia',

                'user_id' => 27,
            ),
            2 =>
            array (
                'address' => 'Hell',
                'amount' => 500,
                'card_number' => NULL,
                'charge' => 40,
                'country' => 'Papua New Guinea',

                'email' => 'freakboss3@gmail.com',
                'first_name' => 'Julius',
                'id' => 17,
                'ip_address' => NULL,
                'last_name' => 'Boom',
                'note' => NULL,
                'payment_type' => NULL,
                'phone' => '2345568',
                'product_id' => 3,
                'quantity' => 2,
                'ref_id' => 'R02diqM8cXivXM2Z',
                'seller_id' => 11,
                'ship_id' => NULL,
                'shipping_fee' => '0',
                'state' => 'Manus',
                'status' => 1,
                'store_id' => NULL,
                'total' => 960,
                'town' => 'Georgia',

                'user_id' => 27,
            ),
            3 =>
            array (
                'address' => 'asdfghs',
                'amount' => 500,
                'card_number' => NULL,
                'charge' => 140,
                'country' => 'Afghanistan',

                'email' => 'sdafghsd@w.com',
                'first_name' => 'wqert',
                'id' => 28,
                'ip_address' => NULL,
                'last_name' => 'sadfg',
                'note' => NULL,
                'payment_type' => NULL,
                'phone' => '2345678986543',
                'product_id' => 3,
                'quantity' => 1,
                'ref_id' => 'WoX29u8VcPbKlDqy',
                'seller_id' => 11,
                'ship_id' => NULL,
                'shipping_fee' => '3000',
                'state' => 'Badakhshan',
                'status' => 1,
                'store_id' => NULL,
                'total' => 3360,
                'town' => 'dfgh',

                'user_id' => NULL,
            ),
            4 =>
            array (
                'address' => 'asdfghs',
                'amount' => 500,
                'card_number' => NULL,
                'charge' => 140,
                'country' => 'Afghanistan',

                'email' => 'sdafghsd@w.com',
                'first_name' => 'wqert',
                'id' => 29,
                'ip_address' => NULL,
                'last_name' => 'sadfg',
                'note' => NULL,
                'payment_type' => NULL,
                'phone' => '2345678986543',
                'product_id' => 3,
                'quantity' => 1,
                'ref_id' => 'WoX29u8VcPbKlDqy',
                'seller_id' => 11,
                'ship_id' => NULL,
                'shipping_fee' => '3000',
                'state' => 'Badakhshan',
                'status' => 1,
                'store_id' => NULL,
                'total' => 3360,
                'town' => 'dfgh',

                'user_id' => NULL,
            ),
            5 =>
            array (
                'address' => 'asdfghs',
                'amount' => 500,
                'card_number' => NULL,
                'charge' => 140,
                'country' => 'Afghanistan',

                'email' => 'sdafghsd@w.com',
                'first_name' => 'wqert',
                'id' => 30,
                'ip_address' => NULL,
                'last_name' => 'sadfg',
                'note' => NULL,
                'payment_type' => NULL,
                'phone' => '2345678986543',
                'product_id' => 3,
                'quantity' => 1,
                'ref_id' => 'WoX29u8VcPbKlDqy',
                'seller_id' => 11,
                'ship_id' => NULL,
                'shipping_fee' => '3000',
                'state' => 'Badakhshan',
                'status' => 1,
                'store_id' => NULL,
                'total' => 3360,
                'town' => 'dfgh',

                'user_id' => NULL,
            ),
            6 =>
            array (
                'address' => 'asdfghs',
                'amount' => 500,
                'card_number' => NULL,
                'charge' => 140,
                'country' => 'Afghanistan',

                'email' => 'sdafghsd@w.com',
                'first_name' => 'wqert',
                'id' => 31,
                'ip_address' => NULL,
                'last_name' => 'sadfg',
                'note' => NULL,
                'payment_type' => NULL,
                'phone' => '2345678986543',
                'product_id' => 3,
                'quantity' => 1,
                'ref_id' => 'WoX29u8VcPbKlDqy',
                'seller_id' => 11,
                'ship_id' => NULL,
                'shipping_fee' => '3000',
                'state' => 'Badakhshan',
                'status' => 1,
                'store_id' => NULL,
                'total' => 3360,
                'town' => 'dfgh',

                'user_id' => NULL,
            ),
            7 =>
            array (
                'address' => 'asdfghjasdfgh',
                'amount' => 500,
                'card_number' => NULL,
                'charge' => 140,
                'country' => 'Albania',

                'email' => 'support@boomchart.net',
                'first_name' => 'asdfg',
                'id' => 32,
                'ip_address' => NULL,
                'last_name' => 'asdfg',
                'note' => NULL,
                'payment_type' => NULL,
                'phone' => '2345678543',
                'product_id' => 3,
                'quantity' => 1,
                'ref_id' => 'zjIGAmxEAkqBDMcI',
                'seller_id' => 11,
                'ship_id' => NULL,
                'shipping_fee' => '3000',
                'state' => 'Delvine',
                'status' => 1,
                'store_id' => NULL,
                'total' => 3360,
                'town' => 'sadfgh',

                'user_id' => NULL,
            ),
            8 =>
            array (
                'address' => 'asdfghjasdfgh',
                'amount' => 500,
                'card_number' => NULL,
                'charge' => 140,
                'country' => 'Albania',

                'email' => 'support@boomchart.net',
                'first_name' => 'asdfg',
                'id' => 33,
                'ip_address' => NULL,
                'last_name' => 'asdfg',
                'note' => NULL,
                'payment_type' => NULL,
                'phone' => '2345678543',
                'product_id' => 3,
                'quantity' => 1,
                'ref_id' => 'zjIGAmxEAkqBDMcI',
                'seller_id' => 11,
                'ship_id' => NULL,
                'shipping_fee' => '3000',
                'state' => 'Delvine',
                'status' => 1,
                'store_id' => NULL,
                'total' => 3360,
                'town' => 'sadfgh',

                'user_id' => NULL,
            ),
            9 =>
            array (
                'address' => 'asdfghjasdfgh',
                'amount' => 500,
                'card_number' => NULL,
                'charge' => 140,
                'country' => 'Albania',

                'email' => 'support@boomchart.net',
                'first_name' => 'asdfg',
                'id' => 34,
                'ip_address' => NULL,
                'last_name' => 'asdfg',
                'note' => NULL,
                'payment_type' => NULL,
                'phone' => '2345678543',
                'product_id' => 3,
                'quantity' => 1,
                'ref_id' => 'zjIGAmxEAkqBDMcI',
                'seller_id' => 11,
                'ship_id' => NULL,
                'shipping_fee' => '3000',
                'state' => 'Delvine',
                'status' => 1,
                'store_id' => NULL,
                'total' => 3360,
                'town' => 'sadfgh',

                'user_id' => NULL,
            ),
            10 =>
            array (
                'address' => NULL,
                'amount' => 300000,
                'card_number' => NULL,
                'charge' => 30000,
                'country' => NULL,

                'email' => 'd@s.com',
                'first_name' => 'dasfg',
                'id' => 35,
                'ip_address' => NULL,
                'last_name' => 'sdfgh',
                'note' => NULL,
                'payment_type' => NULL,
                'phone' => '234567865432',
                'product_id' => 7,
                'quantity' => 1,
                'ref_id' => '2tYSgbm2pIhyz5l5',
                'seller_id' => 41,
                'ship_id' => NULL,
                'shipping_fee' => '0',
                'state' => NULL,
                'status' => 1,
                'store_id' => NULL,
                'total' => 270000,
                'town' => NULL,

                'user_id' => NULL,
            ),
            11 =>
            array (
                'address' => NULL,
                'amount' => 300000,
                'card_number' => NULL,
                'charge' => 30000,
                'country' => NULL,

                'email' => 'a@d.com',
                'first_name' => 'asDF',
                'id' => 36,
                'ip_address' => NULL,
                'last_name' => 'ASDFG',
                'note' => NULL,
                'payment_type' => NULL,
                'phone' => '2345675432',
                'product_id' => 7,
                'quantity' => 1,
                'ref_id' => 'au6xy8JqzMGL7fKF',
                'seller_id' => 41,
                'ship_id' => NULL,
                'shipping_fee' => '0',
                'state' => NULL,
                'status' => 1,
                'store_id' => NULL,
                'total' => 270000,
                'town' => NULL,

                'user_id' => NULL,
            ),
            12 =>
            array (
                'address' => NULL,
                'amount' => 20000,
                'card_number' => NULL,
                'charge' => 0,
                'country' => NULL,

                'email' => NULL,
                'first_name' => NULL,
                'id' => 38,
                'ip_address' => NULL,
                'last_name' => NULL,
                'note' => NULL,
                'payment_type' => NULL,
                'phone' => NULL,
                'product_id' => 16,
                'quantity' => NULL,
                'ref_id' => 'ORD-QPlOPF',
                'seller_id' => 41,
                'ship_id' => NULL,
                'shipping_fee' => NULL,
                'state' => NULL,
                'status' => 1,
                'store_id' => NULL,
                'total' => 0,
                'town' => NULL,

                'user_id' => 41,
            ),
            13 =>
            array (
                'address' => 'sdfg',
                'amount' => 20000,
                'card_number' => NULL,
                'charge' => 2000,
                'country' => 'American Samoa',

                'email' => NULL,
                'first_name' => NULL,
                'id' => 39,
                'ip_address' => NULL,
                'last_name' => NULL,
                'note' => NULL,
                'payment_type' => NULL,
                'phone' => NULL,
                'product_id' => 16,
                'quantity' => 1,
                'ref_id' => 'ORD-DA5kcd',
                'seller_id' => 41,
                'ship_id' => NULL,
                'shipping_fee' => '0',
                'state' => 'Manu\'a',
                'status' => 1,
                'store_id' => NULL,
                'total' => 18000,
                'town' => 'asdfgh',

                'user_id' => 41,
            ),
            14 =>
            array (
                'address' => 'sadf',
                'amount' => 20000,
                'card_number' => NULL,
                'charge' => 2000,
                'country' => 'Albania',

                'email' => 'demo@boomchart.net',
                'first_name' => 'idbjfd',
                'id' => 41,
                'ip_address' => NULL,
                'last_name' => 'jhcdd',
                'note' => NULL,
                'payment_type' => NULL,
                'phone' => NULL,
                'product_id' => 16,
                'quantity' => 1,
                'ref_id' => 'ORD-bhYtqO',
                'seller_id' => 41,
                'ship_id' => NULL,
                'shipping_fee' => NULL,
            'state' => 'Devoll (Bilisht)',
                'status' => 1,
                'store_id' => NULL,
                'total' => 18000,
                'town' => 'sadfg',

                'user_id' => 41,
            ),
            15 =>
            array (
                'address' => 'ZXzcv',
                'amount' => 20000,
                'card_number' => NULL,
                'charge' => 8000,
                'country' => 'Argentina',

                'email' => 'demo@boomchart.net',
                'first_name' => 'idbjfd',
                'id' => 43,
                'ip_address' => NULL,
                'last_name' => 'jhcdd',
                'note' => NULL,
                'payment_type' => NULL,
                'phone' => NULL,
                'product_id' => 16,
                'quantity' => 4,
                'ref_id' => 'ORD-LrQkhA',
                'seller_id' => 41,
                'ship_id' => 3,
                'shipping_fee' => '3200',
                'state' => 'Jujuy',
                'status' => 1,
                'store_id' => NULL,
                'total' => 72000,
                'town' => 'saadfgh',

                'user_id' => 41,
            ),
            16 =>
            array (
                'address' => NULL,
                'amount' => 20000,
                'card_number' => NULL,
                'charge' => 6000,
                'country' => NULL,

                'email' => NULL,
                'first_name' => NULL,
                'id' => 44,
                'ip_address' => NULL,
                'last_name' => NULL,
                'note' => NULL,
                'payment_type' => NULL,
                'phone' => NULL,
                'product_id' => 15,
                'quantity' => 3,
                'ref_id' => 'ORD-zdQdj2',
                'seller_id' => 41,
                'ship_id' => NULL,
                'shipping_fee' => NULL,
                'state' => NULL,
                'status' => 1,
                'store_id' => NULL,
                'total' => 54000,
                'town' => NULL,

                'user_id' => 41,
            ),
            17 =>
            array (
                'address' => NULL,
                'amount' => 20000,
                'card_number' => NULL,
                'charge' => 6000,
                'country' => NULL,

                'email' => NULL,
                'first_name' => NULL,
                'id' => 45,
                'ip_address' => NULL,
                'last_name' => NULL,
                'note' => NULL,
                'payment_type' => NULL,
                'phone' => NULL,
                'product_id' => 15,
                'quantity' => 3,
                'ref_id' => 'ORD-mItFzn',
                'seller_id' => 41,
                'ship_id' => NULL,
                'shipping_fee' => NULL,
                'state' => NULL,
                'status' => 1,
                'store_id' => NULL,
                'total' => 54000,
                'town' => NULL,

                'user_id' => 41,
            ),
            18 =>
            array (
                'address' => NULL,
                'amount' => 2000,
                'card_number' => NULL,
                'charge' => 600,
                'country' => NULL,

                'email' => 'info@boomchart.net',
                'first_name' => 'Rashford',
                'id' => 52,
                'ip_address' => NULL,
                'last_name' => 'kim',
                'note' => NULL,
                'payment_type' => NULL,
                'phone' => NULL,
                'product_id' => 9,
                'quantity' => 3,
                'ref_id' => 'ORD-OspreT',
                'seller_id' => 44,
                'ship_id' => NULL,
                'shipping_fee' => NULL,
                'state' => NULL,
                'status' => 1,
                'store_id' => 3,
                'total' => -600,
                'town' => NULL,

                'user_id' => NULL,
            ),
        ));


    }
}
